export default [
    {
        ND: 1,
        level: 1,
        defense: 18,
        atkBonus: 7,
        strongRes: 7,
        mediumRes: 5,
        weakRes: 0,
        PV: 35,
        CD: 17,
        damage: 8,
    },
    {
        ND: 2,
        level: 1,
        defense: 20,
        atkBonus: 8,
        strongRes: 8,
        mediumRes: 6,
        weakRes: 1,
        PV: 53,
        CD: 18,
        damage: 9,
    },
    {
        ND: 3,
        level: 1,
        defense: 21,
        atkBonus: 9,
        strongRes: 8,
        mediumRes: 6,
        weakRes: 1,
        PV: 79,
        CD: 18,
        damage: 11,
    },
    {
        ND: 4,
        level: 1,
        defense: 22,
        atkBonus: 10,
        strongRes: 9,
        mediumRes: 7,
        weakRes: 2,
        PV: 105,
        CD: 19,
        damage: 12,
    },
    {
        ND: 5,
        level: 1,
        defense: 23,
        atkBonus: 11,
        strongRes: 9,
        mediumRes: 7,
        weakRes: 2,
        PV: 150,
        CD: 19,
        damage: 20,
    },
    {
        ND: 6,
        level: 2,
        defense: 24,
        atkBonus: 12,
        strongRes: 13,
        mediumRes: 11,
        weakRes: 6,
        PV: 180,
        CD: 20,
        damage: 28,
    },
    {
        ND: 7,
        level: 2,
        defense: 27,
        atkBonus: 13,
        strongRes: 13,
        mediumRes: 11,
        weakRes: 6,
        PV: 210,
        CD: 22,
        damage: 31,
    },
    {
        ND: 8,
        level: 2,
        defense: 28,
        atkBonus: 14,
        strongRes: 14,
        mediumRes: 12,
        weakRes: 7,
        PV: 240,
        CD: 23,
        damage: 34,
    },
    {
        ND: 9,
        level: 2,
        defense: 29,
        atkBonus: 15,
        strongRes: 14,
        mediumRes: 12,
        weakRes: 7,
        PV: 270,
        CD: 23,
        damage: 37,
    },
    {
        ND: 10,
        level: 2,
        defense: 31,
        atkBonus: 16,
        strongRes: 15,
        mediumRes: 13,
        weakRes: 8,
        PV: 300,
        CD: 24,
        damage: 40,
    },
    {
        ND: 11,
        level: 2,
        defense: 32,
        atkBonus: 17,
        strongRes: 15,
        mediumRes: 13,
        weakRes: 8,
        PV: 413,
        CD: 24,
        damage: 65,
    },
    {
        ND: 12,
        level: 2,
        defense: 34,
        atkBonus: 18,
        strongRes: 16,
        mediumRes: 14,
        weakRes: 9,
        PV: 450,
        CD: 25,
        damage: 72,
    },
    {
        ND: 13,
        level: 3,
        defense: 35,
        atkBonus: 19,
        strongRes: 19,
        mediumRes: 16,
        weakRes: 12,
        PV: 488,
        CD: 25,
        damage: 79,
    },
    {
        ND: 14,
        level: 3,
        defense: 37,
        atkBonus: 20,
        strongRes: 20,
        mediumRes: 17,
        weakRes: 13,
        PV: 525,
        CD: 26,
        damage: 86,
    },
    {
        ND: 15,
        level: 3,
        defense: 41,
        atkBonus: 21,
        strongRes: 20,
        mediumRes: 17,
        weakRes: 13,
        PV: 563,
        CD: 28,
        damage: 93,
    },
    {
        ND: 16,
        level: 3,
        defense: 44,
        atkBonus: 22,
        strongRes: 21,
        mediumRes: 18,
        weakRes: 14,
        PV: 600,
        CD: 29,
        damage: 100,
    },
    {
        ND: 17,
        level: 3,
        defense: 46,
        atkBonus: 23,
        strongRes: 21,
        mediumRes: 18,
        weakRes: 14,
        PV: 765,
        CD: 29,
        damage: 135,
    },
    {
        ND: 18,
        level: 3,
        defense: 49,
        atkBonus: 24,
        strongRes: 22,
        mediumRes: 19,
        weakRes: 15,
        PV: 810,
        CD: 30,
        damage: 144,
    },
    {
        ND: 19,
        level: 3,
        defense: 50,
        atkBonus: 25,
        strongRes: 22,
        mediumRes: 19,
        weakRes: 15,
        PV: 855,
        CD: 30,
        damage: 153,
    },
    {
        ND: 20,
        level: 3,
        defense: 52,
        atkBonus: 26,
        strongRes: 23,
        mediumRes: 20,
        weakRes: 16,
        PV: 900,
        CD: 31,
        damage: 162,
    },
];